name: Build and Release Mac

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      # https://github.com/marketplace/actions/cached-lfs-checkout
      - name: Checkout code with cached LFS
        uses: nschloe/action-cached-lfs-checkout@v1
      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.0
        with:
           cli: 1.11.1.1149
      - name: Build, package, release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          MAC_VERSION: ${{ matrix.os }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          RELEASE_CHANNEL: ${{ secrets.RELEASE_CHANNEL }}
        run: |
          clojure -T:build ci-build-package-upload :mac-version ${{ matrix.os }}  :dir ${{ matrix.os }}
